name: Deploy Prefect ETL Flow

on:
  push:
    branches:
      - main
    paths:
      - 'getting-started/etl/etl-cicd-pipeline/**'

jobs:
  deploy_flow:
    name: Build and Deploy ETL Flow
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: getting-started/etl/etl-cicd-pipeline

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Prefect Deploy
        uses: PrefectHQ/actions-prefect-deploy@v4
        with:
          deployment-names: etl-cicd-pipeline
          requirements-file-paths: ./etl/etl-cicd-pipeline/requirements.txt
          deployment-file-path: ./etl/etl-cicd-pipeline/prefect.yaml
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
